[project]
name = "texus"
version = "0.1.0"
description = "Runnable Notepad"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [{ name = "Alsefum" } ]
dependencies = [
  "fastapi>=0.115.0",
  "uvicorn[standard]>=0.30.0",
  "toml>=0.10.2",
]